# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-12 10:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routine', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='period',
            name='subject',
            field=models.TextField(),
        ),
        migrations.RemoveField(
            model_name='period',
            name='teachers',
        ),
        migrations.AddField(
            model_name='period',
            name='teachers',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
