# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-12 14:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routine', '0003_auto_20151212_1133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='period',
            name='teachers',
            field=models.TextField(max_length=100),
        ),
    ]
