# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-28 12:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0005_auto_20151228_1225'),
        ('routine', '0005_auto_20151226_0420'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='routine',
            name='notifica_id',
        ),
        migrations.AlterField(
            model_name='period',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classroom.Subject'),
        ),
        migrations.RemoveField(
            model_name='period',
            name='teachers',
        ),
        migrations.AddField(
            model_name='period',
            name='teachers',
            field=models.ManyToManyField(to='classroom.Teacher'),
        ),
    ]
