# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-02 02:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routine', '0006_auto_20151228_1225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='period',
            name='remarks',
            field=models.TextField(blank=True),
        ),
    ]
