# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-04 03:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routine', '0007_auto_20160102_0255'),
    ]

    operations = [
        migrations.AddField(
            model_name='period',
            name='period_type',
            field=models.IntegerField(choices=[(0, 'Lecture'), (1, 'Practical')], default=0),
        ),
    ]
