# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-06 05:08
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('routine', '0009_auto_20160104_0359'),
    ]

    operations = [
        migrations.AddField(
            model_name='routine',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 1, 6, 5, 8, 43, 725337, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='routine',
            name='modified_at',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2016, 1, 6, 5, 8, 48, 237284, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
