# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-11 12:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0016_subject_color'),
        ('routine', '0010_auto_20160106_0508'),
    ]

    operations = [
        migrations.CreateModel(
            name='Elective',
            fields=[
                ('period_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='routine.Period')),
                ('students', models.ManyToManyField(to='classroom.Student')),
            ],
            options={
                'ordering': ['day', 'start_time'],
            },
            bases=('routine.period',),
        ),
    ]
