# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-02 14:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0017_request'),
        ('routine', '0013_auto_20160202_1427'),
    ]

    operations = [
        migrations.CreateModel(
            name='Elective',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.IntegerField()),
                ('end_time', models.IntegerField()),
                ('day', models.IntegerField(choices=[(0, 'Sunday'), (1, 'Monday'), (2, 'Tuesday'), (3, 'Wednesday'), (4, 'Thursday'), (5, 'Friday'), (6, 'Saturday')])),
                ('period_type', models.IntegerField(choices=[(0, 'Lecture'), (1, 'Practical')], default=0)),
                ('remarks', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['day', 'start_time'],
            },
        ),
        migrations.CreateModel(
            name='ElectiveGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
                ('routine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='routine.Routine')),
            ],
        ),
        migrations.AddField(
            model_name='elective',
            name='p_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='routine.ElectiveGroup'),
        ),
        migrations.AddField(
            model_name='elective',
            name='students',
            field=models.ManyToManyField(to='classroom.Student'),
        ),
        migrations.AddField(
            model_name='elective',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classroom.Subject'),
        ),
        migrations.AddField(
            model_name='elective',
            name='teachers',
            field=models.ManyToManyField(blank=True, to='classroom.Teacher'),
        ),
    ]
