# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-18 11:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.IntegerField()),
                ('sender_type', models.IntegerField(choices=[(0, 'USER'), (1, 'CLASS')])),
                ('status', models.IntegerField(choices=[(0, 'Unaccepted'), (1, 'Accepted'), (2, 'Acknowledged')], default=0)),
                ('request_type', models.IntegerField(choices=[(0, 'JOIN_CLASS'), (1, 'JOIN_DEPARTMENT')])),
                ('to', models.IntegerField()),
            ],
        ),
    ]
