# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-12 10:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='class',
            options={'verbose_name_plural': 'classes'},
        ),
        migrations.AlterField(
            model_name='class',
            name='department',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='subject',
            name='department',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='teacher',
            name='department',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
