# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-28 12:25
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0004_auto_20151212_1432'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='class',
            name='notifica_id',
        ),
        migrations.RemoveField(
            model_name='department',
            name='notifica_id',
        ),
        migrations.RemoveField(
            model_name='group',
            name='notifica_id',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='notifica_id',
        ),
        migrations.RemoveField(
            model_name='student',
            name='notifica_id',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='notifica_id',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='notifica_id',
        ),
        migrations.AlterField(
            model_name='class',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='classroom.Department'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='classroom.Department'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='classroom.Department'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
