# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-28 13:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0005_auto_20151228_1225'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='username',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
