# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-02 14:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0010_auto_20160102_1423'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(blank=True, default='avatars/ninja.png', upload_to='avatars/'),
        ),
    ]
