# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-08 11:28
from __future__ import unicode_literals

import classroom.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0012_auto_20160102_1428'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(blank=True, default='avatars/ninja.png', upload_to='avatars/')),
            ],
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='avatar',
        ),
        migrations.AddField(
            model_name='class',
            name='profile',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='classroom.Profile'),
        ),
        migrations.AddField(
            model_name='department',
            name='profile',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='classroom.Profile'),
        ),
        migrations.AddField(
            model_name='organization',
            name='profile',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='classroom.Profile'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='profile',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='classroom.Profile'),
        ),
    ]
