# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-08 11:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0013_auto_20160108_1128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='profile',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='classroom.Profile'),
        ),
        migrations.AlterField(
            model_name='department',
            name='profile',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='classroom.Profile'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='profile',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='classroom.Profile'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='profile',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='classroom.Profile'),
        ),
    ]
