# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-10 13:07
from __future__ import unicode_literals

import classroom.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0015_auto_20160108_1143'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='color',
            field=models.CharField(default=classroom.models.get_random_color, max_length=10),
        ),
    ]
