# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-10 05:57
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('classroom', '0017_request'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organization',
            name='admins',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='profile',
        ),
        migrations.AddField(
            model_name='department',
            name='admins',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
