# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-13 13:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0019_class_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teacher',
            options={},
        ),
    ]
