# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-18 11:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0020_auto_20160213_1301'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Request',
        ),
    ]
