# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-23 13:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0021_delete_request'),
    ]

    operations = [
        migrations.CreateModel(
            name='Elective',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.CharField(default='A', max_length=30)),
                ('subject', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='classroom.Subject')),
            ],
        ),
    ]
