# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-23 13:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0022_elective'),
    ]

    operations = [
        migrations.AddField(
            model_name='elective',
            name='p_class',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='classroom.Class', verbose_name='class'),
            preserve_default=False,
        ),
    ]
