# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-23 13:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0024_auto_20160223_1325'),
    ]

    operations = [
        migrations.AddField(
            model_name='elective',
            name='students',
            field=models.ManyToManyField(blank=True, to='classroom.Student'),
        ),
    ]
