# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-02 08:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20160102_0829'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='tags',
        ),
        migrations.AddField(
            model_name='post',
            name='tags',
            field=models.TextField(blank=True),
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
