# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-06 05:08
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_auto_20160102_1411'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ('posted_at',)},
        ),
        migrations.RenameField(
            model_name='assignment',
            old_name='posted_on',
            new_name='posted_at',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='posted_on',
            new_name='posted_at',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='posted_on',
            new_name='posted_at',
        ),
        migrations.RenameField(
            model_name='submission',
            old_name='posted_on',
            new_name='posted_at',
        ),
        migrations.AddField(
            model_name='assignment',
            name='modified_at',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2016, 1, 6, 5, 8, 20, 607179, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='comment',
            name='modified_at',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2016, 1, 6, 5, 8, 24, 537837, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='modified_at',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2016, 1, 6, 5, 8, 31, 944490, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='submission',
            name='modified_at',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2016, 1, 6, 5, 8, 37, 648185, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
