# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-06 06:46
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0007_auto_20160106_0508'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('body', models.TextField()),
                ('posted_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('event_at', models.DateField()),
                ('tags', models.TextField(blank=True)),
                ('posted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('modified_at', 'posted_at'),
            },
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ('modified_at', 'posted_at')},
        ),
        migrations.RemoveField(
            model_name='post',
            name='event_on',
        ),
    ]
