# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-08 12:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0015_auto_20160108_1143'),
        ('posts', '0010_auto_20160108_1203'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='profile',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='classroom.Profile'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='profile',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='classroom.Profile'),
            preserve_default=False,
        ),
    ]
