# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-19 05:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0011_auto_20160108_1209'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assignment',
            options={'ordering': ('modified_at', 'posted_at')},
        ),
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ('modified_at', 'posted_at')},
        ),
        migrations.AlterModelOptions(
            name='submission',
            options={'ordering': ('modified_at', 'posted_at')},
        ),
        migrations.AddField(
            model_name='assignment',
            name='links',
            field=models.TextField(blank=True, default='[]'),
        ),
        migrations.AddField(
            model_name='comment',
            name='links',
            field=models.TextField(blank=True, default='[]'),
        ),
        migrations.AddField(
            model_name='event',
            name='links',
            field=models.TextField(blank=True, default='[]'),
        ),
        migrations.AddField(
            model_name='post',
            name='links',
            field=models.TextField(blank=True, default='[]'),
        ),
        migrations.AddField(
            model_name='submission',
            name='links',
            field=models.TextField(blank=True, default='[]'),
        ),
        migrations.AlterField(
            model_name='post',
            name='tags',
            field=models.TextField(blank=True, default='[]'),
        ),
    ]
