# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-30 06:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0012_auto_20160119_0552'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assignment',
            options={'ordering': ('-modified_at', '-posted_at')},
        ),
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ('-modified_at', '-posted_at')},
        ),
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ('-modified_at', '-posted_at')},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ('-modified_at', '-posted_at')},
        ),
        migrations.AlterModelOptions(
            name='submission',
            options={'ordering': ('-modified_at', '-posted_at')},
        ),
    ]
